name: Flask CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Récupérer le code du dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Installer Python 3.14
      - name: Set up Python 3.14
        uses: actions/setup-python@v4
        with:
          python-version: 3.14

      # Mettre à jour pip
      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      # Installer les dépendances
      - name: Install dependencies
        run: pip install flask


      # Démarrer le serveur Flask en arrière-plan
      - name: Run Flask server
        run: |
          export FLASK_APP=app.py
          export FLASK_ENV=development
          flask run &
          sleep 5   # attendre que le serveur démarre

      # Tester le serveur avec curl
      - name: Test server with curl
        run: curl http://127.0.0.1:5000/

      # Lancer les tests automatiques avec pytest
      - name: Run tests
        run: python -m pytest
